[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"

# Remappings
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

# Optimizer
optimizer = true
optimizer_runs = 200

# Networks
[rpc_endpoints]
polygon_amoy = "${POLYGON_AMOY_RPC}"

[etherscan]
polygon_amoy = { key = "${POLYGONSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
